### ISSUE TITLE
Add new manifest property for system wide purge uninstallation

### ISSUE THREAD

**Issue by Ash258** [ScoopInstaller/Scoop#2782]
Purge uninstalling is already option, and delete only scoops data (which is OK and expected), but some applications use registry, system drive, environmnets, which cannot be changed / forced to delete or are create after first application running.

When you are purge uninstalling application, you expect to delete everything related to that application. So if application create some "junk" (for example folder in AppData) you should be able to set:

```json
"purgeuninstallerOrsimmilar": [
    "Remove-Item \"$env:APPDATA\\someapp\" -Recurse",
    "Remove-Item \"HKCU:\\SOmeValue\" -Recurse",
    "Remove-Item \"$env:USERPROFILE\\.favoritercfiles\""
]
```

And make eveything in same state as before installation.

Example vscode (Other electron application, Wavebox, Rambox, ...) use AppData for storing cache, settings, ... and when purge uninstalling vscode you should be able to delete them.

**Comment by wenmin92** [comment]
Well, hope achieve it earlier.

**Comment by Ash258** [comment]
This is not needed to be only script. For better manifest ergonomics it could be usual application junk (registry, Appdata, Userconfig folder, ...)

```yml
uninstaller:
  purge: # This will be executed after successful uninstallation process.
    script: [] # <string | Array of strings> Same as installer script. For advanced cleaning
    registry: [] # <string | Array of strings> with PSDrive format `HKCU:\jfksdjf`, this will need to handle admin access check to all hives excluding HKCU
    appdata: [] # <string | Array of strings> folders inside $env:APPDATA
    localappdata: [] # <string | Array of strings> folders inside $env:LOCALAPPDATA
```

All types are not exclusive, it will be executed in some order

Example for vscode-insiders it could look like this:

```yml
uninstaller:
  purge:
    user: .vscode-insiders
    appdata: Visual Studio Code - Insiders
    registry:
      - HKCR\*\shell\Open with Code Insiders
      - HKCR\*\shell\Open with Code Insiders\command
      - HKCR\Directory\shell\Open with Code &Insiders
      - HKCR\Directory\shell\Open with Code &Insiders\command
      - HKCR\Directory\Background\shell\Open with Code &Insiders
      - HKCR\Directory\Background\shell\Open with Code &Insiders\command
```
