### ISSUE TITLE
travis-ci: The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by zaoqi** [ScoopInstaller/Scoop#3616]
.travis.yml
```
language: c
matrix:
  include:
    - os: windows
      install:
        - powershell "Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser"
        - powershell "iex (new-object net.webclient).downloadstring('https://get.scoop.sh')"
        - export PATH="$PATH:"~/scoop/shims/
        - scoop install make nodejs yarn
    - os: osx
      osx_image: xcode10.3
      addons:
        homebrew:
          packages:
            - make
            - nodejs
            - npm
            - yarn
    - os: linux
      dist: bionic
      sudo: required
      addons:
        apt:
          sources:
            - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
              key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
          packages:
            - make
            - nodejs
            - npm
            - yarn
script:
  - make all
  - make test
```

log
```
$ scoop install make nodejs yarn
Installing 'make' (4.2.1) [64bit]
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\travis\scoop\apps\scoop\current\lib\core.ps1:802 char:21
+     $last_update = (scoop config lastupdate)
+                     ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\travis\scoop\apps\scoop\current\lib\core.ps1:818 char:9
+         scoop config lastupdate $now.ToString('o')
+         ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\travis\scoop\apps\scoop\current\libexec\scoop-install.ps1:71 char:5
+     scoop update
+     ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
 
Downloading https://downloads.sourceforge.net/project/ezwinports/make-4.2.1-without-guile-w32-bin.zip (336.5 KB)...
Checking hash of make-4.2.1-without-guile-w32-bin.zip ... ok.
Extracting make-4.2.1-without-guile-w32-bin.zip ... done.
Linking ~\scoop\apps\make\current => ~\scoop\apps\make\4.2.1
Creating shim for 'make'.
...
```
