### ISSUE TITLE
[Bug] Scoop erased parts of my USERPROFILE folder

### ISSUE THREAD

**Issue by Earthnuker** [ScoopInstaller/Scoop#4696]
#### Current Behavior
When running `scoop update '*'` after failing to update FastCopy scoop appears to hang, turns out it had started deleting my %USERPROFILE% folder

#### Expected Behavior
scoop should not delete my userprofile folder

#### Additional context/output
```
Updating 'fastcopy' (3.92 -> 4.0.2)
Downloading new version
FastCopy4.0.2_installer.exe (3,3 MB) [============================================================================================================================================] 100%
Checking hash of FastCopy4.0.2_installer.exe ... ok.
Uninstalling 'fastcopy' (3.92)
Removing shim 'FastCopy.exe'.
Removing shim 'FastCopy.shim'.
Removing shim 'FastCopy.ps1'.
Unlinking ~\scoop\apps\fastcopy\current
Installing 'fastcopy' (4.0.2) [64bit]
Loading FastCopy4.0.2_installer.exe from cache
Running pre-install script...
Running installer script...
ERROR Exit code was -1073740791!
<Hangs, ProcessHacker shows powershell process accessing many files in %USERPROFILE%>
```

### System details

**Windows version:** 10

**OS architecture:** 64-bit

**PowerShell version:** 5.1.19041.1320

**Additional software:** <NA>

#### Scoop Configuration
```
```

**Comment by HUMORCE** [comment]
cannot reproduce.

is there more information?

**Comment by Earthnuker** [comment]
oh, it didn't remove the files, it moved them to the FastCopy install folder, so it might be an issue with the install script

**Comment by HUMORCE** [comment]
$HOME\* moved to <scoop>\apps\fastcopy\<version>\ , right?

i will check it

**Comment by Earthnuker** [comment]
looks like the problem is here: https://github.com/ScoopInstaller/Extras/blob/701487bc6669bcaefdc196d3c9539c8915a5f9d6/bucket/fastcopy.json#L21
 `$extract_dir` was set to an empty string `$dir` didn't exist, resulting in `Get-ChildItem` returning the contents of the current directory

```powershell
Get-ChildItem (Get-ChildItem -Path "C:\Windows\system32\" -Filter "FastCopy*" -Directory).FullName
```

**Comment by HUMORCE** [comment]
try:
```
scoop uninstall fastcopy
scoop install https://gist.githubusercontent.com/HUMORCE/35fe1177de6ce87e755c9cc713858b45/raw/964477f649faeacb3476b5b63233b1b8f67974ad/fastcopy.json
```

**Comment by Earthnuker** [comment]
```
> scoop install https://gist.githubusercontent.com/HUMORCE/35fe1177de6ce87e755c9cc713858b45/raw/964477f649faeacb3476b5b63233b1b8f67974ad/fastcopy.json
WARN  Purging previous failed installation of fastcopy.
Uninstalling 'fastcopy' ().
'fastcopy' was uninstalled.
Installing 'fastcopy' (4.0.2) [64bit]
Loading FastCopy4.0.2_installer.exe from cache
Checking hash of FastCopy4.0.2_installer.exe ... ok.
Running pre-install script...
Running installer script...
ERROR Exit code was -1073740791!
Linking ~\scoop\apps\fastcopy\current => ~\scoop\apps\fastcopy\4.0.2
Creating shim for 'FastCopy'.
Can't shim 'FastCopy.exe': File doesn't exist.
```

**Comment by HUMORCE** [comment]
emmm, $home\\* files will not be removed (or moved to another location) now, but you will still failed to install, i dont know why you cannot execute the installer correctly. `*installer.exe /EXTRACT64`

try run `SCOOP\cache\fastcopy#4.0.2#https_fastcopy.jp_archive_FastCopy4.0.2_installer.exe` directly to see what happen

**Comment by Earthnuker** [comment]
Looks like the installer itself crashes when trying to extract the files, doing it through the GUI works, using `/EXTRACT64` results in
```
EXCEPTION_DEBUG_INFO:
           dwFirstChance: 0
           ExceptionCode: C0000409 (STATUS_STACK_BUFFER_OVERRUN)
          ExceptionFlags: 00000001
        ExceptionAddress: 0043D481 fastcopy#4.0.2#https_fastcopy.jp_archive_fastcopy4.0.2_installer.0043D481
        NumberParameters: 1
ExceptionInformation[00]: 00000005
Last chance exception on 0043D481 (C0000409, STATUS_STACK_BUFFER_OVERRUN)!
```
so that appears to be a FastCopy issue
